### ISSUE TITLE
repo: remove big files

### ISSUE THREAD

**Issue by slint** [asclepias/asclepias-data-formatter#1]
In order to keep the repository light and quick to clone/download, it would be better to remove the "big" zip files and make them part of some release artefact instead. This of course means "rewriting" git history since the files were added in at the beginning of the repo, but since we're only 4 commits in, it might be better to do so now.

**Comment by augustfly** [comment]
who is responsible for this re-write, @slint?

**Comment by slint** [comment]
I'll be doing it at the beginning of next week, when we'll finish with importing the ADS metadata in the currently running broker.

**Comment by slint** [comment]
Rewrite done, if you've cloned this repository locally, delete and clone it again or `git reset --hard origin/master`. 

Removed files were extracted at: https://github.com/asclepias/asclepias-data-formatter/releases/tag/2018.05.29
